server:
  port: 8888
spring:
  application:
    name: config-cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yjpress/netprint.git
          search-paths: config-file/**
          default-label: main
          username: jun
          password: 1234
